name: Release

on:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  release:
    permissions:
      attestations: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and release plugin
        uses: grafana/plugin-actions/build-plugin@main
        with:
          policy_token: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
          sign_root_urls: https://grafana.myrspoven.se/,http://grafana.myrspoven.se:3000/,https://testgrafana.myrspoven.se/,http://testgrafana.myrspoven.se:3000/
          attestation: 'true'
